'use client';

import clsx from 'clsx';
import { User, Bot } from 'lucide-react';

interface AuthorTypeBadgeProps {
  authorType: 'human' | 'bot' | string;
  size?: 'sm' | 'md' | 'lg';
  showLabel?: boolean;
  className?: string;
}

export function AuthorTypeBadge({
  authorType,
  size = 'sm',
  showLabel = true,
  className,
}: AuthorTypeBadgeProps) {
  const isHuman = authorType === 'human';

  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5 gap-1',
    md: 'text-sm px-2.5 py-1 gap-1.5',
    lg: 'text-base px-3 py-1.5 gap-2',
  };

  const iconSize = {
    sm: 12,
    md: 14,
    lg: 16,
  };

  return (
    <span
      title={
        isHuman
          ? 'This problem was posted by a human user'
          : 'This problem was generated by an AI bot'
      }
      className={clsx(
        'inline-flex items-center rounded-full font-medium whitespace-nowrap',
        sizeClasses[size],
        isHuman
          ? 'bg-blue-950 text-blue-300 ring-1 ring-blue-800'
          : 'bg-purple-950 text-purple-300 ring-1 ring-purple-800',
        className
      )}
    >
      {isHuman ? (
        <User size={iconSize[size]} strokeWidth={2.5} />
      ) : (
        <Bot size={iconSize[size]} strokeWidth={2.5} />
      )}
      {showLabel && (
        <span>{isHuman ? 'Human Post' : 'Bot Post'}</span>
      )}
    </span>
  );
}
